export const CodeLanguages = {
  "Plain text": "txt",
  HTML: "html",
  XML: "xml",
  SVG: "svg",
  MathML: "mathml",
  SSML: "ssml",
  RSS: "rss",
  CSS: "css",
  "C-like": "clike",
  JavaScript: "js",
  ABAP: "abap",
  ABNF: "abnf",
  AL: "al",
  ANTLR4: "g4",
  "Apache Configuration": "apacheconf",
  APL: "apl",
  AQL: "aql",
  Arduino: "ino",
  ARFF: "arff",
  "ARM Assembly": "arm-asm",
  Arturo: "art",
  AsciiDoc: "adoc",
  "ASP.NET (C#)": "aspnet",
  "6502 Assembly": "asm6502",
  "Atmel AVR Assembly": "asmatmel",
  AutoHotkey: "autohotkey",
  AutoIt: "autoit",
  AviSynth: "avs",
  "Avro IDL": "avdl",
  AWK: "awk",
  GAWK: "gawk",
  Shell: "sh",
  BASIC: "basic",
  BBcode: "bbcode",
  BBj: "bbj",
  BNF: "bnf",
  RBNF: "rbnf",
  BQN: "bqn",
  "BSL (1C:Enterprise)": "bsl",
  OneScript: "oscript",
  "C#": "dotnet",
  "C++": "cpp",
  CFScript: "cfc",
  CIL: "cil",
  "Cilk/C": "cilk-c",
  "Cilk/C++": "cilk",
  CMake: "cmake",
  COBOL: "cobol",
  CoffeeScript: "coffee",
  Concurnas: "conc",
  "Content-Security-Policy": "csp",
  "CSS Extras": "css-extras",
  CSV: "csv",
  CUE: "cue",
  DataWeave: "dataweave",
  DAX: "dax",
  "Django/Jinja2": "jinja2",
  "DNS zone file": "dns-zone",
  Docker: "dockerfile",
  "DOT (Graphviz)": "gv",
  EBNF: "ebnf",
  EditorConfig: "editorconfig",
  EJS: "ejs",
  "Embedded Lua templating": "etlua",
  ERB: "erb",
  "Excel Formula": "xls",
  "F#": "fsharp",
  "Firestore security rules": "firestore-security-rules",
  "FreeMarker Template Language": "ftl",
  "GameMaker Language": "gamemakerlanguage",
  "GAP (CAS)": "gap",
  "G-code": "gcode",
  GDScript: "gdscript",
  GEDCOM: "gedcom",
  gettext: "po",
  GLSL: "glsl",
  GN: "gni",
  "GNU Linker Script": "ld",
  "Go module": "go-mod",
  GraphQL: "graphql",
  Handlebars: "hbs",
  Haskell: "hs",
  HCL: "hcl",
  HLSL: "hlsl",
  HTTP: "http",
  "HTTP Public-Key-Pins": "hpkp",
  "HTTP Strict-Transport-Security": "hsts",
  IchigoJam: "ichigojam",
  "ICU Message Format": "icu-message-format",
  Idris: "idr",
  ".ignore": "ignore",
  ".gitignore": "gitignore",
  ".hgignore": "hgignore",
  ".npmignore": "npmignore",
  "Inform 7": "inform7",
  JavaDoc: "javadoc",
  "JavaDoc-like": "javadoclike",
  "Java stack trace": "javastacktrace",
  JQ: "jq",
  JSDoc: "jsdoc",
  "JS Extras": "js-extras",
  JSON: "json",
  "Web App Manifest": "webmanifest",
  JSON5: "json5",
  JSONP: "jsonp",
  "JS stack trace": "jsstacktrace",
  "JS Templates": "js-templates",
  "Keepalived Configure": "keepalived",
  "Kotlin Script": "kts",
  Kotlin: "kt",
  "KuMir (КуМир)": "kum",
  LaTeX: "latex",
  TeX: "tex",
  ConTeXt: "context",
  LilyPond: "ly",
  Lisp: "emacs-lisp",
  "LLVM IR": "llvm",
  "Log file": "log",
  LOLCODE: "lolcode",
  "Magma (CAS)": "magma",
  Markdown: "md",
  "Markup templating": "markup-templating",
  MATLAB: "matlab",
  MAXScript: "maxscript",
  MEL: "mel",
  METAFONT: "metafont",
  MongoDB: "mongodb",
  MoonScript: "moon",
  N1QL: "n1ql",
  N4JS: "n4jsd",
  "Nand To Tetris HDL": "nand2tetris-hdl",
  "Naninovel Script": "nani",
  NASM: "nasm",
  NEON: "neon",
  nginx: "nginx",
  NSIS: "nsis",
  "Objective-C": "objc",
  OCaml: "ocaml",
  OpenCL: "opencl",
  OpenQasm: "qasm",
  "PARI/GP": "parigp",
  "Object Pascal": "objectpascal",
  "PATROL Scripting Language": "psl",
  "PC-Axis": "px",
  PeopleCode: "pcode",
  PHP: "php",
  PHPDoc: "phpdoc",
  "PHP Extras": "php-extras",
  PlantUML: "plantuml",
  "PL/SQL": "plsql",
  PowerQuery: "mscript",
  PowerShell: "powershell",
  PromQL: "promql",
  ".properties": "properties",
  "Protocol Buffers": "protobuf",
  PureBasic: "pbfasm",
  PureScript: "purs",
  Python: "py",
  "Q#": "qs",
  "Q (kdb+ database)": "q",
  QML: "qml",
  Racket: "rkt",
  "Razor C#": "razor",
  "React JSX": "jsx",
  "React TSX": "tsx",
  "Ren'py": "rpy",
  ReScript: "res",
  "reST (reStructuredText)": "rest",
  "Robot Framework": "robot",
  Ruby: "rb",
  SAS: "sas",
  "Sass (Sass)": "sass",
  "Sass (SCSS)": "scss",
  "Shell session": "shellsession",
  SML: "sml",
  "SML/NJ": "smlnj",
  "Solidity (Ethereum)": "sol",
  "Solution file": "sln",
  "Soy (Closure Template)": "soy",
  SPARQL: "rq",
  "Splunk SPL": "splunk-spl",
  "SQF: Status Quo Function (Arma 3)": "sqf",
  SQL: "sql",
  "Stata Ado": "stata",
  "Structured Text (IEC 61131-3)": "iecst",
  SuperCollider: "sclang",
  "Systemd configuration file": "systemd",
  "T4 templating": "t4-templating",
  "T4 Text Templates (C#)": "t4",
  "T4 Text Templates (VB)": "t4-vb",
  TAP: "tap",
  "Template Toolkit 2": "tt2",
  TOML: "toml",
  trickle: "trickle",
  troy: "troy",
  TriG: "trig",
  TypeScript: "ts",
  TSConfig: "tsconfig",
  UnrealScript: "uc",
  "UO Razor Script": "uorazor",
  URI: "uri",
  URL: "url",
  "VB.Net": "vbnet",
  VHDL: "vhdl",
  vim: "vim",
  "Visual Basic": "vb",
  VBA: "vba",
  WebAssembly: "wasm",
  "Web IDL": "webidl",
  WGSL: "wgsl",
  "Wiki markup": "wiki",
  "Wolfram language": "wl",
  "Mathematica Notebook": "nb",
  XeoraCube: "xeoracube",
  "XML doc (.net)": "xml-doc",
  "Xojo (REALbasic)": "xojo",
  XQuery: "xquery",
  YAML: "yml",
  YANG: "yang",
};
