import type { LocaleDict } from "@/types";

export const ENG_LANG: LocaleDict = {
  LOCALE: "en-US",
  LANGUAGE: "English",
  LOADING: "Loading...",
  INTRO: {
    FEATURED: {
      TITLE: "Featured Records",
      DESC: "Display up to 10 records checked as favorite.",
    },
    LATEST: {
      TITLE: "Latest Records",
      DESC: "Displays up to 7 most recent records per subtype.",
    },
    ENTIRE: {
      TITLE: "Entire Records",
      DESC: "Display all records regardless of type.",
    },
    READ_MORE: "Read More",
    BOOK: {
      SUBTITLE_1: "Take a look all the Book Records",
      SUBTITLE_2: "based on all the Words and World of sentences.",
      TITLE: "Book Records.",
      DESCRIPTION_PREFIX: "",
      DESCRIPTION_HIGHLIGHT_1: "Archive",
      DESCRIPTION_HIGHLIGHT_2: "All Books",
      DESCRIPTION_SUFFIX: "connected by small and big words.",
    },
    ENGINEERING: {
      SUBTITLE: "Browsing all the engineering related records you have learned",
      TITLE: "Software Engineering.",
      DESCRIPTION_PREFIX: "",
      DESCRIPTION_HIGHLIGHT_1: "An archive",
      DESCRIPTION_HIGHLIGHT_2: "knowledge, information, studies",
      DESCRIPTION_SUFFIX: "of good",
      DESCRIPTION_END: "learned and recorded",
    },
    GENERAL: {
      SUBTITLE_1: "Take a look all the General Records",
      SUBTITLE_2: "based on all the waves Life has been comming through.",
      TITLE: "Gerneral Records.",
      DESCRIPTION_PREFIX: "",
      DESCRIPTION_HIGHLIGHT_1: "Archive",
      DESCRIPTION_HIGHLIGHT_2: "All Records",
      DESCRIPTION_SUFFIX: "of",
      DESCRIPTION_END: "connected by small and big waves.",
    },
  },
  COMMON: {
    ALL: "All",
    OPTIONS: "Options",
    TAGS: "All Tags",
    TYPES: "All Types",
    NO_TAG: "NoTag",
    CATEGORY: "Category",
    SHARE: "Share Record",
    URL_COPIED: "URL has copied!",
    COPYRIGHT_NOTICE:
      "All articles in this blog, except for special statements, adopt BY-NC-SA agreement. Please indicate the source!",
    DEBUG_OPEN: "Debug",
    DEBUG_CLOSE: "Close",
    LOADING: "Loading...",
    ANNOUNCEMENT: "Announcement",
    NO_RECORD_FOUND: "No relevant archive records found.",
  },
  RECORD: {
    LAST_EDITED_TIME: "Last edited",
    VIEW: "View",
    MINUTE: "min",
    READING_TIME: "Reading Time",
    WORD_COUNT: "W.C.",
    TABLE_OF_CONTENTS: "Table Of Contents",
  },
  LOCKED: {
    LOCKED: "Private",
    PASSWORD_SUBMIT: "Please enter your password",
    PASSWORD_ERROR: "Password does not match",
    ARCHIVE_LOCK_TIPS: "This is a private post.",
    SUBMIT: "Submit",
  },
  PAGINATION: {
    PREV: "Prev",
    NEXT: "Next",
    PAGE: "Page",
    OF: "of",
  },
  SEARCH: {
    ARCHIVE: "Search Archive",
    TAGS: "Search in Tags",
    CATEGORY: "Search in Category",
    SEARCH_TERM: "Search term",
    ENTER_SEARCH_TERM: "Search archive...",
  },
  ERROR: {
    ERROR_OCCURRED: "Something went wrong",
    INVALID_RECORD: "Invalid Record",
  },
  FETCH: {
    ERROR_OCCURRED: "Error occurred while parsing data",
    PAGE_DATA_FAILED: "Failed to fetch page data for pageId",
    INVALID_RECORD: "Invalid Record",
  },
  SITE: {
    BACK: "Back",
    TOP: "Top",
    SETTINGS: "Site Settings",
    LOCALE: "Language settings",
    DISPLAY_LIGHT: "Display brightness settings",
    LANG_CHANGE_SUCCESS_MSG: "The Site Language has been changed",
    DEBUG_PANEL_TITLE: "Site Configuration [blog.config.js]",
  },
};
