import { Feather } from "lucide-react";

export const ENG_LANG = {
  LOCALE: "en-US",
  LOADING: "Loading...",
  INTRO: {
    FEATURED: {
      TITLE: "Featured Records",
      DESC: "Display the records checked as favorite.",
    },
    LATEST: {
      TITLE: "Latest Records",
      DESC: "Displays up to 7 most recent records per subtype.",
    },
    ENTIRE: {
      TITLE: "Entire Records",
      DESC: "Display all records regardless of type.",
    },
    READ_MORE: "Read More",
  },
  COMMON: {
    ALL: "All",
    OPTIONS: "Options",
    MORE: "More",
    NO_MORE: "No More",
    LATEST_RECORDS: "Latest records",
    TAGS: "Tags",
    NO_TAG: "NoTag",
    CATEGORY: "Category",
    SHARE: "Share",
    URL_COPIED: "URL has copied!",
    TABLE_OF_CONTENTS: "Table Of Contents",
    RELATE_RECORDS: "Relate Records",
    COPYRIGHT: "Copyright",
    AUTHOR: "Author",
    URL: "URL",
    RECORDS: "Records",
    VISITORS: "Visitors",
    VIEWS: "Views",
    COPYRIGHT_NOTICE:
      "All articles in this blog, except for special statements, adopt BY-NC-SA agreement. Please indicate the source!",
    ARCHIVE_DETAIL: "Archive Details",
    PASSWORD_SUBMIT: "Please enter your password",
    PASSWORD_ERROR: "Password does not match",
    ARCHIVE_LOCK_TIPS: "This is a private post.",
    SUBMIT: "Submit",
    RECORD_TIME: "Record on",
    LAST_EDITED_TIME: "Last edited",
    VIEW: "View",
    COMMENTS: "Comments",
    RECENT_COMMENTS: "Recent Comments",
    DEBUG_OPEN: "Debug",
    DEBUG_CLOSE: "Close",
    ANNOUNCEMENT: "Announcement",
    START_READING: "Start Reading",
    MINUTE: "min",
    READING_TIME: "Reading Time",
    WORD_COUNT: "W.C.",
    LOCKED: "private",
    SEARCH_TERM: "Search term",
    NO_RECORD_FOUND: "No relevant archive records have been created.",
    ENTER_SEARCH_TERM: "Search archive...",
    INVALID_RECORD: "Invalid Record",
    ERROR_OCCURRED: "Something went wrong",
  },
  PAGINATION: {
    PREV: "Prev",
    NEXT: "Next",
  },
  SEARCH: {
    ARTICLES: "Search Articles",
    TAGS: "Search in Tags",
    CATEGORY: "Search in Category",
  },
  SITE: {
    BACK: "Back",
    TOP: "Top",
    SETTINGS: "Site Settings",
    LOCALE: "Language settings",
    DISPLAY_LIGHT: "Display brightness settings",
    LANG_CHANGE_SUCCESS_MSG: "The Site Language has been changed",
  },
};
