import type { LocaleDict } from "@/types";

export const KOR_LANG: LocaleDict = {
  LOCALE: "kr-KR",
  LANGUAGE: "한국어",
  LOADING: "로딩중...",
  INTRO: {
    FEATURED: {
      TITLE: "주요글",
      DESC: "favourite으로 체크된 문서 10개를 가져옵니다.",
    },
    LATEST: {
      TITLE: "최근글",
      DESC: "서브타입별로 가장 최근에 작성된 문서 7개를 표시합니다.",
    },
    ENTIRE: {
      TITLE: "전체글",
      DESC: "모든 문서를 확인해보세요",
    },
    READ_MORE: "자세히 보기",
    BOOK: {
      SUBTITLE_1: "Take a look all the Book Docs",
      SUBTITLE_2: "based on all the Words and World of sentences.",
      TITLE: "Book Docs.",
      DESCRIPTION_PREFIX: "언어와 문장들로",
      DESCRIPTION_HIGHLIGHT_1: "이루어진",
      DESCRIPTION_HIGHLIGHT_2: "아카이브.",
      DESCRIPTION_SUFFIX: "connected by small and big words.",
    },
    ENGINEERING: {
      SUBTITLE: "Browsing all the engineering related Docs you have learned",
      TITLE: "Software Engineering.",
      DESCRIPTION_PREFIX: "배우고 기록한 좋은",
      DESCRIPTION_HIGHLIGHT_1: "지식, 정보, 앎",
      DESCRIPTION_HIGHLIGHT_2: "아카이브.",
      DESCRIPTION_SUFFIX: "에 대한",
    },
    GENERAL: {
      SUBTITLE_1: "Take a look all the General Docs",
      SUBTITLE_2: "based on all the waves Life has been comming through.",
      TITLE: "Gerneral Docs.",
      DESCRIPTION_PREFIX: "일상의 작은 조각들로",
      DESCRIPTION_HIGHLIGHT_1: "이루어진",
      DESCRIPTION_HIGHLIGHT_2: "아카이브.",
      DESCRIPTION_SUFFIX: "",
    },
  },
  COMMON: {
    ALL: "전체",
    OPTIONS: "옵션",
    TAGS: "전체 태그",
    TYPES: "전체 타입",
    NO_TAG: "태그없음",
    CATEGORY: "카테고리",
    SHARE: "공유하기",
    URL_COPIED: "URL이 복사됐습니다",
    COPYRIGHT_NOTICE:
      "이 블로그의 모든 기사는 특별한 진술을 제외하고 BY-NC-SA 계약을 채택하고 있습니다. 출처를 알려주세요.",
    DEBUG_OPEN: "디버그",
    DEBUG_CLOSE: "닫기",
    LOADING: "로딩중...",
    ANNOUNCEMENT: "공지사항",
    NO_DOCS_FOUND: "관련 아카이브 문서가 없습니다.",
  },
  DOCS: {
    LAST_EDITED_TIME: "최종 수정일",
    VIEW: "조회수",
    MINUTE: "분",
    READING_TIME: "읽는 시간",
    WORD_COUNT: "글자수",
    TABLE_OF_CONTENTS: "목차",
  },
  LOCKED: {
    LOCKED: "비공개",
    PASSWORD_SUBMIT: "비밀번호를 입력하세요.",
    PASSWORD_ERROR: "비밀번호가 일치하지않습니다.",
    ARCHIVE_LOCK_TIPS: "비공개 게시글입니다.",
    SUBMIT: "제출",
  },
  PAGINATION: {
    PREV: "이전",
    NEXT: "다음",
    PAGE: "페이지",
    OF: "중의",
  },
  SEARCH: {
    ARCHIVE: "아카이브 검색",
    TAGS: "태그 검색",
    CATEGORY: "카테고리 검색",
    SEARCH_TERM: "검색어",
    ENTER_SEARCH_TERM: "검색어를 입력하세요.",
  },
  ERROR: {
    ERROR_OCCURRED: "문제가 발생했습니다",
    INVALID_DOC: "유효하지 않은 문서입니다.",
  },
  FETCH: {
    ERROR_OCCURRED: "데이터 파싱 중 오류가 발생했습니다.",
    PAGE_DATA_FAILED: "페이지 데이터 파싱 중 오류가 발생했습니다.",
    INVALID_DOC: "유효하지 않은 문서입니다.",
  },
  SITE: {
    BACK: "뒤로",
    TOP: "위로",
    SETTINGS: "사이트 설정",
    LOCALE: "언어 설정",
    DISPLAY_LIGHT: "디스플레이 밝기 설정",
    LANG_CHANGE_SUCCESS_MSG: "사이트 언어가 변경되었습니다.",
    DEBUG_PANEL_TITLE: "사이트 구성 [blog.config.js]",
  },
};
