export const KOR_LANG = {
  LOCALE: "kr-KR",
  LOADING: "로딩중...",
  INTRO: {
    FAVORITE_RECORDS: "주요 레코드",
    FAVORITE_RECORDS_DESC: "favourite으로 체크된 레코드들을 가져옵니다.",
    RECENT_RECORDS: "최근 레코드",
    RECENT_RECORDS_DESC:
      "서브타입별로 가장 최근에 작성된 레코드 7개를 표시합니다.",
    ENTIRE_RECORDS: "전체 레코드",
    ENTIRE_RECORDS_DESC: "모든 레코드를 확인해보세요",
    READ_MORE: "자세히 보기",
  },
  COMMON: {
    ALL: "전체",
    OPTIONS: "옵션",
    MORE: "더보기",
    NO_MORE: "더보기 종료",
    LATEST_RECORDS: "최근 레코드",
    TAGS: "태그",
    NO_TAG: "태그없음",
    CATEGORY: "카테고리",
    SHARE: "공유",
    URL_COPIED: "URL이 복사됐습니다",
    TABLE_OF_CONTENTS: "목차",
    RELATE_RECORDS: "관련 레코드",
    COPYRIGHT: "저작권",
    AUTHOR: "작성자",
    URL: "URL",
    RECORDS: "Records",
    VISITORS: "방문자",
    VIEWS: "조회수",
    COPYRIGHT_NOTICE:
      "이 블로그의 모든 기사는 특별한 진술을 제외하고 BY-NC-SA 계약을 채택하고 있습니다. 출처를 알려주세요.",
    ARCHIVE_DETAIL: "Archive 상세",
    PASSWORD_SUBMIT: "비밀번호를 입력하세요.",
    PASSWORD_ERROR: "비밀번호가 일치하지않습니다.",
    ARCHIVE_LOCK_TIPS: "비공개 게시글입니다.",
    SUBMIT: "제출",
    RECORD_TIME: "작성일",
    LAST_EDITED_TIME: "최종 수정일",
    VIEW: "조회수",
    COMMENTS: "댓글",
    RECENT_COMMENTS: "최근 댓글",
    DEBUG_OPEN: "디버그",
    DEBUG_CLOSE: "닫기",
    ANNOUNCEMENT: "공지사항",
    START_READING: "읽기 시작",
    MINUTE: "분",
    WORD_COUNT: "글자수",
    LOCKED: "비공개",
    SEARCH_TERM: "검색어",
    NO_RECORD_FOUND: "관련 아카이브 레코드가 없습니다.",
    ENTER_SEARCH_TERM: "검색어를 입력하세요.",
    INVALID_RECORD: "유효하지 않은 레코드입니다.",
  },
  PAGINATION: {
    PREV: "이전",
    NEXT: "다음",
  },
  SEARCH: {
    ARCHIVE: "아카이브 검색",
    TAGS: "태그 검색",
    CATEGORY: "카테고리 검색",
  },
  SITE: {
    BACK: "뒤로",
    TOP: "위로",
    SETTINGS: "사이트 설정",
    LOCALE: "언어 설정",
    DISPLAY_LIGHT: "디스플레이 밝기 설정",
    LANG_CHANGE_SUCCESS_MSG: "사이트 언어가 변경되었습니다.",
  },
};
