export const ENG_LANG = {
  LOCALE: "en-US",
  MENU: {
    RANDOM_PAGE: "Go to Random Page",
    CATEGORY: "Category",
    TAGS: "Tags",
    COPY_URL: "Copy URL",
    DARK_MODE: "Dark Mode",
    LIGHT_MODE: "Light Mode",
    LANG_CHANGE: "Language => Kor",
  },
  NAV: {
    INDEX: "Home",
    RSS: "RSS",
    SEARCH: "Search",
    ABOUT: "About",
    MAIL: "E-Mail",
    RECORDS: "RECORDS",
    DEVPROJECT: "Dev Project",
    ENGINEERING: "Engineering",
  },
  PAGE: {
    DEVPROJECT: `<span className="font-semibold ">Archive</span> of
          <span className="font-semibold "> Dev</span> projects connected by small and big learnings`,
  },
  LOADING: "Loading...",
  COMMON: {
    MORE: "More",
    NO_MORE: "No More",
    LATEST_RECORDS: "Latest records",
    TAGS: "Tags",
    NO_TAG: "NoTag",
    CATEGORY: "Category",
    SHARE: "Share",
    URL_COPIED: "URL has copied!",
    TABLE_OF_CONTENTS: "Table Of Contents",
    RELATE_RECORDS: "Relate Records",
    COPYRIGHT: "Copyright",
    AUTHOR: "Author",
    URL: "URL",
    RECORDS: "Records",
    ARTICLE: "Article",
    VISITORS: "Visitors",
    VIEWS: "Views",
    COPYRIGHT_NOTICE:
      "All articles in this blog, except for special statements, adopt BY-NC-SA agreement. Please indicate the source!",
    ARTICLE_DETAIL: "Article Details",
    PASSWORD_SUBMIT: "Please enter your password",
    PASSWORD_ERROR: "Password does not match",
    ARTICLE_LOCK_TIPS: "This is a private post.",
    SUBMIT: "Submit",
    RECORD_TIME: "Post on",
    LAST_EDITED_TIME: "Last edited",
    VIEW: "view",
    COMMENTS: "Comments",
    RECENT_COMMENTS: "Recent Comments",
    DEBUG_OPEN: "Debug",
    DEBUG_CLOSE: "Close",
    ANNOUNCEMENT: "Announcement",
    START_READING: "Start Reading",
    MINUTE: "min",
    WORD_COUNT: "W.C.",
    LOCKED: "private",
    SEARCH_TERM: "Search term",
    NO_RECORD_FOUND: "No relevant archive records have been created.",
    ENTER_SEARCH_TERM: "Search term...",
    INVALID_RECORD: "Invalid Record",
  },
  PAGINATION: {
    PREV: "Prev",
    NEXT: "Next",
  },
  SEARCH: {
    ARTICLES: "Search Articles",
    TAGS: "Search in",
  },
  RECORD: {
    BACK: "Back",
    TOP: "Top",
  },
};
