export const KOR_LANG = {
  LOCALE: "kr-KR",
  MENU: {
    RANDOM_PAGE: "Go to Random Page",
    CATEGORY: "Category",
    TAGS: "Tags",
    COPY_URL: "Copy URL",
    DARK_MODE: "Dark Mode",
    LIGHT_MODE: "Light Mode",
  },
  NAV: {
    INDEX: "Home",
    RSS: "RSS",
    SEARCH: "Search",
    ABOUT: "About",
    MAIL: "E-Mail",
    RECORDS: "Record",
    DEVPROJECT: "Dev 프로젝트",
  },
  PAGE: {
    DEVPROJECT: `작고 큰 배움으로 연결된
          <span className="font-semibold "> Dev</span> 프로젝트에 대한
          <span className=" dark:text-[#ffffff] font-bold">
            &nbsp;아카이브.
          </span>`,
  },
  COMMON: {
    MORE: "더보기",
    NO_MORE: "더보기 종료",
    LATEST_RECORDS: "최근 레코드",
    TAGS: "Tags",
    NO_TAG: "NoTag",
    CATEGORY: "Category",
    SHARE: "Share",
    URL_COPIED: "URL이 복사되었습니다",
    TABLE_OF_CONTENTS: "Catalog",
    RELATE_RECORDS: "관련된 레코드",
    COPYRIGHT: "저작권",
    AUTHOR: "작성자",
    URL: "URL",
    RECORDS: "Records",
    ARTICLE: "Article",
    VISITORS: "방문자",
    VIEWS: "조회수",
    COPYRIGHT_NOTICE:
      "이 블로그의 모든 기사는 특별한 진술을 제외하고 BY-NC-SA 계약을 채택하고 있습니다. 출처를 알려주세요.",
    ARTICLE_DETAIL: "Article Details",
    PASSWORD_SUBMIT: "비밀번호를 입력하세요.",
    PASSWORD_ERROR: "비밀번호가 일치하지않습니다.",
    ARTICLE_LOCK_TIPS: "비공개 게시글입니다.",
    SUBMIT: "제출",
    POST_TIME: "작성일",
    LAST_EDITED_TIME: "최종수정일",
    VIEW: "뷰",
    COMMENTS: "댓글",
    RECENT_COMMENTS: "최근 댓글",
    DEBUG_OPEN: "디버그",
    DEBUG_CLOSE: "닫기",
    ANNOUNCEMENT: "공지사항",
    START_READING: "읽기시작",
    MINUTE: "분",
    WORD_COUNT: "W.C.",
    LOCKED: "비공개",
    NO_RECORD_FOUND: "레코드를 찾을 수 없습니다.",
  },
  PAGINATION: {
    PREV: "이전",
    NEXT: "다음",
  },
  SEARCH: {
    ARTICLES: "레코드 검색",
    TAGS: "Search in",
  },
  RECORD: {
    BACK: "뒤로",
    TOP: "위로",
  },
};
